doctrine_phpcr:
    odm:
        auto_generate_proxy_classes: false
        metadata_cache_driver:
            type: service
            id: doctrine_phpcr.system_cache_provider
    session:
        backend:
            caches:
                meta: doctrine_phpcr.meta_cache_provider
                nodes: doctrine_phpcr.nodes_cache_provider

services:
    doctrine_phpcr.meta_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@doctrine_phpcr.meta_cache_pool'
    doctrine_phpcr.nodes_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@doctrine_phpcr.nodes_cache_pool'
    doctrine_phpcr.system_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@doctrine_phpcr.system_cache_pool'

framework:
    cache:
        pools:
            doctrine_phpcr.meta_cache_pool:
                adapter: cache.app
            doctrine_phpcr.nodes_cache_pool:
                adapter: cache.app
            doctrine_phpcr.system_cache_pool:
                adapter: cache.system
